### ISSUE TITLE
install instructions ?

### ISSUE THREAD

**Issue by colindaven** [gpertea/tiebrush#4]
Hi, interesting looking software, thanks.

Did I overlook install instructions ?

Trying just a make, I first got an error on ../htslib not being present. After suppling that one, I got this one ... 

Has the file needed been renamed as `build_bwlib.sh` ?

```
tiebrush$ make
cd ../htslib && ./build_lib.sh
/bin/sh: 1: ./build_lib.sh: not found
make: *** [Makefile:170: ../htslib/libhts.a] Error 127

```

Or is build_lib.sh supposed to exist in the external directory htslib (it does not at present).

Thanks

**Comment by gpertea** [comment]
Sorry, I should have updated the README: this is no longer the current repository for this project, please use https://github.com/alevar/tiebrush for this project - the code and documentation is updated there.
